Add SharedTelemetryConfig API
upbound/up-sdk-go pull request #76
Opened 2024-04-11 13:56 UTC by lsviben

### Description of your changes

Adds SharedTelemetryConfig API.

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- ~[] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.~

### How has this code been tested

Generated the crd in spaces, and tested it in a local cluster creating the example SharedTelemetryConfig from the [design doc](https://docs.google.com/document/d/1GCaXqcRv0aB9Bf3FrfTHvxxJ0LooZYYRO7xcHSl95X0/edit).

2024-04-11 13:58 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	// TODO(lsviben): Add validation that checks if pipeline values are present in the exporters field.
I played around with CEL to do this but I am not sure if its possible or we need to go through a webhook.

For now I had smt like:
`self.pipelines.metrics.all(x, has(self.exporters[x]))`
But that doesnt seem to work.

2024-04-11 14:09 UTC, jeanduplessis requested changes

2024-04-11 14:09 UTC, jeanduplessis commented on apis/observability/v1alpha1/telemetry_types.go
> +const SharedTelemetryConfigKey = "spaces.upbound.io/sharedbackup"
```suggestion
const SharedTelemetryConfigKey = "spaces.upbound.io/sharedtelemetryconfig"
```

2024-04-11 14:09 UTC, jeanduplessis commented on apis/observability/v1alpha1/telemetry_types.go
> +// +kubebuilder:printcolumn:name="Provisioned",type="string",JSONPath=`.metadata.annotations.sharedbackup\.internal\.spaces\.upbound\.io/provisioned`
```suggestion
// +kubebuilder:printcolumn:name="Selected",type="string",JSONPath=`.metadata.annotations.sharedtelemetryconfig\.internal\.spaces\.upbound\.io/selected`
// +kubebuilder:printcolumn:name="Failed",type="string",JSONPath=`.metadata.annotations.sharedtelemetryconfig\.internal\.spaces\.upbound\.io/failed`
// +kubebuilder:printcolumn:name="Provisioned",type="string",JSONPath=`.metadata.annotations.sharedtelemetryconfig\.internal\.spaces\.upbound\.io/provisioned`
```

2024-04-11 15:36 UTC, sttts commented on apis/observability/v1alpha1/telemetry_types.go
> +	Exporters common.JSONObject `json:"exporters"`
map[string]Export

type Export common.JSONObject

2024-04-11 15:36 UTC, sttts commented on apis/observability/v1alpha1/telemetry_types.go
> +	Pipeline Pipeline `json:"pipeline"`
is this optional? Should be a pointer.

2024-04-11 15:41 UTC, sttts commented on apis/observability/v1alpha1/telemetry_types.go
> +	Metrics []string `json:"metrics"`
Same below.

2024-04-11 15:41 UTC, sttts commented on apis/observability/v1alpha1/telemetry_types.go
> +	Traces []string `json:"traces"`
omitempty if it is optional

2024-04-11 15:43 UTC, sttts commented on apis/observability/v1alpha1/telemetry_types.go
> +	// TODO(lsviben): Add validation that checks if pipeline values are present in the exporters field.
See my comment about the type of Exporters. The system has to know that it is a map. Then you can check for keys.

2024-04-11 15:48 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	Metrics []string `json:"metrics"`
> Is this easy to check with CEL?

Not sure, ref: https://github.com/upbound/up-sdk-go/pull/76#discussion_r1561069470

Ill dig and test a bit more but not sure if you can check dynamically for a field presence?

2024-04-12 09:07 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	// TODO(lsviben): Add validation that checks if pipeline values are present in the exporters field.
Now it works 🎉 . Needed to add maxItems, maxProperties to make it happy but its in reasonable limits.

2024-04-12 09:13 UTC, lsviben commented on apis/observability/v1alpha1/export.go
> +type Export common.JSONObject
Copied over the methods from common.JSONObject that I believe are needed. LMK if I was too eager

2024-04-13 10:25 UTC, phisco commented on apis/observability/v1alpha1/telemetry_types.go
> +const SharedTelemetryConfigKey = "spaces.upbound.io/sharedtelemetryconfig"
SharedTelemetryConfigLabelKey? Just for consistency with other label keys

2024-04-13 10:25 UTC, phisco commented on apis/observability/v1alpha1/telemetry_types.go
> +// SharedTelemetryConfigKey is the label key used to identify Controlplanes that are
Is it for controlplanes or resources created by this config for each controlplane? 🤔

2024-04-15 08:42 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +// SharedTelemetryConfigKey is the label key used to identify Controlplanes that are
Good point, actually when i think about it, it should be both for the Controlplanes that are selected, to mark that their telemetry is configured by this SharedTelemetryConfig, and for the resource that they are creating and managing (OpenTelemetryCollector). Ill reword it.

Maybe there is a way not to mark the ctp at all ill think about it. But for now its convenient to notice conflicts between sharedtelemetryconfigs.

2024-04-15 08:54 UTC, phisco commented on apis/observability/v1alpha1/telemetry_types.go
> +// SharedTelemetryConfigKey is the label key used to identify Controlplanes that are
I'd go with an internal annotation if we need to mark a controlplane as configured. Do we do the same for shared secrets?

2024-04-15 08:57 UTC, turkenh commented on apis/observability/v1alpha1/export.go
> +type Export common.JSONObject
Did we consider going structured instead of free-form here? I mean using a well-defined schema for the exporters we know we are supporting...

2024-04-15 08:57 UTC, turkenh commented on apis/observability/v1alpha1/export.go
> +type Export common.JSONObject
This may or may not be crucial depending on us successfully propagating an invalid configuration back or not.

2024-04-15 13:16 UTC, lsviben commented on apis/observability/v1alpha1/export.go
> +type Export common.JSONObject
Discussed offline with Hasan:

As the otel operator and the otel collector pod are not accessible to the users, debugging invalid configurations becomes difficult. So one option would be to do validation based on structured fields, and this way inform users when their configs are invalid. But this doesnt cover things like typos in target urls and similar.

Another option would be to display the last few lines of the otel-collector pod logs when there is a failure. This is a simpler approach and covers more cases. Tested it out with an invalid field name. Seems that it does the validating for us so we dont need to do it. 
```
2024/04/15 12:56:11 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': error reading configuration for "otlp/spaces": 1 error(s) decoding:

* '' has invalid keys: tes
```

2024-04-16 11:56 UTC, turkenh approved these changes
Looking good. 
Nothing blocking, just left a few thoughts/nits.

2024-04-16 11:56 UTC, turkenh commented on apis/observability/v1alpha1/telemetry_types.go
> +	Exporters map[string]Export `json:"exporters"`
Why not the following and remove `export.go` ? 

```suggestion
	Exporters map[string]common.JSONObject `json:"exporters"`
```

2024-04-16 11:56 UTC, turkenh commented on apis/observability/v1alpha1/telemetry_types.go
> +	Pipeline *Pipeline `json:"pipeline,omitempty"`
thought: Considering [where](https://github.com/upbound/spaces/blob/f44e527d97e97aeeda6c27af045788cf46dd0459/cluster/charts/spaces/templates/observability/collector-spaces.yaml#L39) these will be injected at the end, what do you think about going with `exportPipeline` instead ?

2024-04-16 11:56 UTC, turkenh commented on apis/observability/v1alpha1/telemetry_types.go
> +	// +kubebuilder:validation:MaxItems=20
nit: I cannot think of a reason to have more than 3 exporters ATM, so, we could definitely go with a lower limit like 10. Same applies to other limits.

2024-04-16 11:56 UTC, turkenh commented on apis/observability/v1alpha1/telemetry_types.go
> +// SharedTelemetryConfigKey is the label key used to identify Controlplanes that are
As we discussed offline yesterday, we could go with owner refs on the namespaced `OpenTelemetryCollector` CRs. This way, we won't need additional labels on `ControlPlanes` or `OpenTelemetryCollector`.

2024-04-16 12:10 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	Pipeline *Pipeline `json:"pipeline,omitempty"`
That would make sense, it also will reduce possible confusion with the pipeline itself.

2024-04-18 13:23 UTC, sttts commented on apis/observability/v1alpha1/export.go
> +type Export common.JSONObject
The later sounds very brittle. Are we sure we can't do better?

2024-04-18 14:06 UTC, sttts commented on apis/observability/v1alpha1/telemetry_types.go
> +	// +kubebuilder:validation:MaxItems=10
why ten and not seven?

2024-04-18 14:09 UTC, sttts commented on apis/observability/v1alpha1/telemetry_types.go
> +}
why a non-standard type?

2024-04-18 14:10 UTC, sttts commented on apis/observability/v1alpha1/telemetry_types.go
> +	ReasonConfigurationValid = "Valid"
not seeing a reason field for all of these in the condition type.

2024-04-18 14:17 UTC, phisco commented on apis/observability/v1alpha1/telemetry_types.go
> +	Exporters map[string]Export `json:"exporters"`
no need for the alias, you can set +kubebuilder:pruning:PreserveUnknownFields as you are already doing here and that will work.

2024-04-18 19:16 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	Exporters map[string]Export `json:"exporters"`
I thought so as well but it doesnt. If I generate it with `map[string]common.JSONObject`, the `x-kubernetes-preserve-unknown-fields: true` gets removed from the `additionalProperties`. And then nested objects under `exporters` dont work.

```
                   additionalProperties:
-                    description: Export defines the telemetry exporter configuration.
+                    description: |-
+                      JSONObject represents any valid JSON value of an object.
+                      These types are supported: bool, int64, float64, string, []interface{}, map[string]interface{} and nil.
                     type: object
-                    x-kubernetes-preserve-unknown-fields: true
```
For example this works:
```yaml
  exporters:
    otlphttp: {}
```

But this fails:
```yaml
  exporters:
    otlphttp:
      headers:
         api-key: bob
```
with 
```
": strict decoding error: unknown field "spec.exporters.otlphttp.endpoint", unknown field "spec.exporters.otlphttp.headers"
```

2024-04-18 19:31 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	// +kubebuilder:validation:MaxItems=10
Started with 20, after a [suggestion](https://github.com/upbound/up-sdk-go/pull/76#discussion_r1567223102) moved to 10. Can be 7 I guess as well?

Anyway it should be a number that seems reasonable for the amount of exporters people would define. 

IMO I dont see people defining more then a few, but would feel safer making the limit a bit bigger then expected.

2024-04-18 22:33 UTC, phisco commented on apis/observability/v1alpha1/telemetry_types.go
> +	Exporters map[string]Export `json:"exporters"`
Why map[string]JSONObject and not just JSONObject? 🤔

2024-04-19 06:48 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	Exporters map[string]Export `json:"exporters"`
The CEL rule breaks then because its not a map.

2024-04-19 07:46 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	ReasonConfigurationValid = "Valid"
Didnt use yet in controller so didnt notice 🤦 

Reworked it now.

2024-04-19 07:50 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	Provisioned []string `json:"provisioned,omitempty"`
For now this is just a set of provisioned controlplanes. 

Debating in my head if to also expand this and give it conditions. 

For example between just creating the OpenTelemetry Collector the condition is still "Provisioning", until we can check that the operator successfully the otel-collector pod and its all alive and working. 
It may be clearer when I come to this part in the controller, so Ill update it.

2024-04-19 20:13 UTC, turkenh commented on apis/observability/v1alpha1/export.go
> +type Export common.JSONObject
I agree that it is quite brittle. 

Taking a closer look at this and will try to see if there is a feasible way to validate the config with an admission webhook or sth similar.

2024-04-20 12:25 UTC, turkenh commented on apis/observability/v1alpha1/telemetry_types.go
> +	Exporters map[string]Export `json:"exporters"`
I am working on adding admission webhooks for more advanced validations (i.e. [validating](https://github.com/upbound/up-sdk-go/pull/76#discussion_r1572899359) the export configurations), we can drop CEL rules and cover this validation there in code. 

So, we can simplify what is here as in the first comment in that case?

2024-04-20 13:48 UTC, turkenh commented on apis/observability/v1alpha1/export.go
> +type Export common.JSONObject
I could find a way to validate individual export configs by importing the relevant export package in go code:
- running validate commands in respective packages to validate schema.
- pushing a test metric and checking if its successful.

> running validate commands in respective packages to validate schema.

The only problem so far is we need to import the exporters go code, so, it is not feasible to do it for all type of exporters.
Currently, I am thinking to implement this for `otlphttp` (i.e. newrelic) and `datadog` exporters to start with. This would mean, we won’t support other exporters out of the box which should be fine as we were targeting only these for 1.3. Later, we can add more support.

Just pushed a commit for validating schema part: https://github.com/upbound/spaces/pull/876/commits/312cf7c0e9fcaff2b2652621d4e132fbcac4511c

> pushing a test metric and checking if its successful.

This is still open. I am not sure if this is something to happen in admission level, or should we do it in the reconciler and report a condition like “ConfigurationValid” :thinking_face:

2024-04-21 12:16 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	Exporters map[string]Export `json:"exporters"`
Great. Yeah we can simplify it then 🎉

2024-04-21 12:18 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +// SharedTelemetryConfigKey is the label key used to identify Controlplanes that are
Update here: 
We forgot that owner refs dont work cross-namespace 🤦 , so we are back at the original idea

2024-04-22 05:47 UTC, turkenh commented on apis/observability/v1alpha1/telemetry_types.go
> +	var objs = make([]client.Object, len(s.Items))
Why not just `s.Items` ?

2024-04-22 05:48 UTC, turkenh commented on apis/observability/v1alpha1/telemetry_types.go
> +func (s *SharedTelemetryConfigList) Objects() []client.Object {
Why not just `sharedTelemetryConfigList.Items` ?

2024-04-22 06:17 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +func (s *SharedTelemetryConfigList) Objects() []client.Object {
added it to satisfy [this](https://github.com/upbound/spaces/blob/360b39207ed745c2d653e75b9afef5f2743faa2a/internal/controller/events.go#L22) to use [EnqueueObjectsFromNamespaceOnEvent](https://github.com/upbound/spaces/blob/360b39207ed745c2d653e75b9afef5f2743faa2a/internal/controller/events.go#L45), which seems the standard way to do it in spaces. 

Didnt dig in why that one is not using `.Items`, maybe can be simplified.

2024-04-22 10:21 UTC, turkenh commented on apis/observability/v1alpha1/telemetry_types.go
> +	Exporters map[string]Export `json:"exporters"`
Pushed a commit.

2024-04-22 10:41 UTC, turkenh approved these changes
Looking good 👍 
I would suggest merging this and open follow up issues if we need further changes during development.

2024-04-22 10:42 UTC, lsviben commented on apis/observability/v1alpha1/telemetry_types.go
> +	Provisioned []string `json:"provisioned,omitempty"`
Talked offline with Hasan. 
We will mark as Provisioned those otel-collectors which status has 1/1 ready pods, as there are no other conditions or anything else we could check. From the user endpoint, as we have SELECTED, PROVISIONED and FAILED, it will be visible that some resources are selected, but not yet fully provisioned.

2024-04-22 10:51 UTC, jeanduplessis approved these changes

2024-04-22 10:54 UTC, merged